### ISSUE TITLE
Pen/Highlighter is in use when Type is selected in Draw menu

### ISSUE THREAD

**Issue by magic-ian** [patrikx3/onenote#163]
Behaviour:

- On startup, the mouse defaults to the Pen cursor with pen drawing functionality, even though when you check under the Draw menu, Type is selected under the Draw menu (unexpected)
- When you select Pen or Highlighter from any of the other options, the mouse uses the Pen/Highlighter cursor, has pen/highlighter drawing functionality, and selects the Pen/Highlighter tool under the Draw menu respectively (expected)
   - When you draw something using the Pen/Highlighter cursor, after releasing the mouse pointer, the menu switches to highlighting Type even though the cursor & functionality is still on Pen/Highlighter respectively; if you hold down the mouse to draw something else it temporarily switches to the appropriate tool under the Draw menu (unexpected)
- When you select Eraser, under the Draw menu Eraser gets selected, the mouse switches to the eraser cursor, but the functionality is both that of Eraser and Type simultaneously (unexpected)
   - When you erase something, similar to above, the Draw menu switches to type, but the cursor still displays an Eraser, the functionality is still both Eraser & Type simultaneously, and when you click the mouse to erase again, the Draw menu temporarily switches to the Eraser tool until you release the mouse click (unexpected)
   
I checked with the online editor on the browser on the same computer, and the behaviour there functioned exactly as it should. This didn't used to be an issue when I first downloaded the Snap to my Debian bookworm based machine, but since recent versions the issue persists even after a reinstall.

**Comment by noob-dood** [comment]
I'm running into the same problem.

**Comment by Demonsvols** [comment]
Hi,
I've got the same problem too, with the snap version on Ubuntu 20.04 LTS
I've also got the same problem when i use OneNote directly in chromium, but not in firefox. So maybe it has to do with Electron / Chromium directly...

**Comment by nikobockerman** [comment]
Hi, I wonder if @p3x-robot misunderstood the reported problem. Based on the screenshot, I guess so.

The bug is not that drawing wouldn't work in Pen mode.

The bug is that even when Type mode is selected, the behavior is still as if Pen mode had been selected: clicking with mouse will draw instead of placing typing cursor to where was clicked.

And another closely related issue which also is a workaround to the main issue:
- Eraser mode actually behaves as combined Eraser and Type mode: it eraser drawings, but also places cursor.

So the workaround is to always use Eraser mode when desiring to move text cursor with mouse: requires selecting Eraser after every restart and you can't really use the drawing functionalities together with text.

**Comment by nikobockerman** [comment]
This bug is still present in the latest v2022.10.111 version.

My workaround has been to actually stop using P3X OneNote and instead use OneNote in browser tab: that's overall less annoying than working around this bug in the application.

**Comment by chasehas** [comment]
I have the same issue, though it is definitely a Chromium bug - I get the same behavior on Chrome/Edge/P3X.

**Comment by s-fedosov** [comment]
In native (? don't know, maybe it is an highly customized electron application underneath) application in preferences you can select not to use Pen by default. At least on Mac OS.

On web-version we do not have such menu and in browsers - Opera and min tested - i have "pre-selected" "Pen-by-default". Which is annoying.
I believe it is not chromium/electron bug, but a bug in web-version of One Note Application itself.

Since Microsoft for sure intended to bury down "pc-style workflow" (они там ебанулись в край со своей windows 11) they will ofcorse refuse to review and fix this behavior. And this bug can be fixed only by overriding this logic.

Can it be performed on this application easily? only @p3x-robot can tell... and mabe he can fix this, i hope.

**Comment by s-fedosov** [comment]
I do not have a pen too. But application just ignores this fact and thinks that "mouse is pointing device, right? lets assume that all pointing devices are PEN and screw all thing up". So application runs by default in pen-mode and tries to draw if i create new note and try to click on any empty space in note-pane.

**Comment by s-fedosov** [comment]
to make it clear about what we talking about
https://www.youtube.com/watch?v=xtr3pRlhpIE

but with small difference - text input method shows as selectable and in-fact it visually selected by-default, but if you move mouse pointer over note pane it (mouse pointer) have round shape and if you make usual right click instead of putting **text-mode** cursor in that position, application just puts a big-fat black dot there. And while you pressing left mouse button input method (in draw menu, that is) switches automagically to pencil symbol (pen-mode) and draw line while you keeping left button pressed. And when you release mouse button input method jumps back to text-mode (that was visually selected before).

And in order to make usual text notes i have to click on header of the note, then press tab key and then use only direction keys on my keyboard for navigation actions, avoiding using mouse at all.

Again, in _native_ application everything works smoothly and mouse work as intended - it selects the text if you drag cursor via pressing left mouse button and puts cursor in pointon position if you just left-click there.

**Comment by s-fedosov** [comment]
Trying to help there:
Issue **can be reproduced** on chrome on linux (Version 111.0.5563.64 (Official Build) (64-bit)) and on electron 23.1.4 for linux.

And I was **unable** to reproduce this issue on current versions of Vivaldi for linux/mac/windows, Edge for linux/mac/windows, Opera for mac/linux.

Hopefully @p3x-robot will fix it as we help a bit to nail this bug.

**Comment by samsonluk** [comment]
I can get the same results using Edge Version 131.0.2903.112 (Official build) (64-bit) installed on my Chromebook running Debian GNU/Linux 12 (bookworm) 6.6.50-05090-g02ec56928355 terminal.

**Comment by samsonluk** [comment]
This bug still hasn't been fixed. As of today, I'm getting the same results using Edge Version 131.0.2903.112 (official build) (64-bit) on my Chromebook running Debian GNU/Linux 12 (bookworm) 6.6.50-05090-g02ec56928355 terminal.
