### ISSUE TITLE
Permanent Drawing Mode

### ISSUE THREAD

**Issue by duketjs** [patrikx3/onenote#189]
I have just installed P3X-OneNote via the latest .deb build.
I noticed that my mouse is permanently on drawing mode.
No matter how many times I have selected the Type mode under the Draw menu, my mouse cursor is still on drawing mode.
Is this a bug or is there a shortcut key to perform the switch which I don't know about.
Looking forward to responses.

**Comment by mirage335** [comment]
I am also experiencing this!

The cause is using a 'tablet' style absolute mouse. I cannot figure out how to configure OneNote Web, or any web browser to disregard this and allow text cursor use instead of pen. Deselecting 'Draw with Touch' does NOT help.

Interestingly, FireFox does not have this issue.
