### ISSUE TITLE
Pen / Tablet Inking Features

### ISSUE THREAD

**Issue by MyriaCore** [patrikx3/onenote#39]
## Description of problem
In OG OneNote, you can draw with a pen tablet by just drawing on the screen, erase your ink by holding down a button and drawing or using the eraser, and lasso select and right click by pressing another button and circling your objects. This is all done via the Windows Ink API, and it would complete my transition to linux (and probably a lot of others') if this functionality was available via this app.

## Descrition of Solution
I'm not too familiar with linux API's, but I'm pretty sure [libwacom](https://github.com/linuxwacom/libwacom/wiki), [xf86-input-wacom](https://github.com/linuxwacom/xf86-input-wacom/wiki/Building-The-Driver), or something like that to achieve what the windows ink API is doing. It could probably be done by force switching the tab to draw and selecting the 'last selected tool' or something along those lines via automated browser movements, and then allowing the user to fiddle with what the buttons are doing in a settings menu.
The [linuxwacom](https://linuxwacom.github.io/) website seems to be an okay starting resource.

**Comment by kaliiiiiiiiii** [comment]
> given, this is a simple wrapper of the online one note version, it would not be easy to implement this request. of course if someone understand how it works, i am sure it can be done.

For chromium//electron on Wayland, I guess this would fail at [crbugs#40282832](https://issues.chromium.org/issues/40282832).
Not sure about support on X11.

Suppose that basis for implementation of this would be 
1. **Debian**-based [wiki.debian.org/TabletAndTouchScreen](https://wiki.debian.org/TabletAndTouchScreen)
   1. `libinput` for Wayland
   2. `xf86-input` for X11
3. Alternative: Libwacom

See also [Wacom_Serial_Tablet_PC_Stylus](https://www.thinkwiki.org/wiki/Wacom_Serial_Tablet_PC_Stylus)

@p3x-robot Is there any chance this issue could be re-opened? This is a missing feature which keeps me from moving to linux completely, since lots of institutions such as schools rely on drawing on OneNote.

Especially useful to implement would be (prioritized): 
1. Automatically switch to drawing mode for stylus
2. Support for `erase` and `lasso selection` button (configurable)
3. Pressure-based line thickness
